name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        echo "Creating resource group..."
        az group create \
          --name my-resource-group \
          --location eastus

    - name: Deploy Bicep template
      run: |
        echo "Deploying Bicep template..."
        az deployment group create \
          --resource-group my-resource-group \
          --template-file infra/main.bicep \
          --parameters @infra/parameters.json

    - name: List Resources in Resource Group
      run: |
        echo "Listing resources in the group..."
        az resource list --resource-group my-resource-group

    - name: Install Azure CLI Data Factory Extension
      run: |
        echo "Installing Azure CLI Data Factory extension..."
        az extension add --name datafactory --yes

    # Steps to deploy Linked Service and Datasets
    - name: Get Storage Account Key
      id: storage_key
      run: |
        echo "Getting storage account key..."
        STORAGE_KEY=$(az storage account keys list --resource-group my-resource-group --account-name datavalidation456 --query "[0].value" -o tsv)
        # Use environment file for output
        echo "key=$STORAGE_KEY" >> $GITHUB_OUTPUT

    - name: Deploy Azure Blob Storage Linked Service
      run: |
        echo "Deploying Azure Blob Storage Linked Service..."
        # Read the properties object directly from the JSON file using jq
        # Ensure jq is installed or use alternative parsing if needed
        # Assuming jq is available in the runner environment
        properties_content=$(jq -c '.properties' infra/pipelines/linkedservice_blobstorage.json)

        # Replace placeholders within the properties object
        properties_content=${properties_content/<STORAGE_ACCOUNT_NAME>/datavalidation456}
        properties_content=${properties_content/<STORAGE_ACCOUNT_KEY>/${{ steps.storage_key.outputs.key }}}

        az datafactory linked-service create \
          --factory-name DataValidationFactoryUnique \
          --resource-group my-resource-group \
          --linked-service-name AzureBlobStorageLinkedService \
          --properties "$properties_content" # Pass only the properties object

    - name: Deploy FonteDados Dataset
      run: |
        echo "Deploying FonteDados Dataset..."
        # Extract properties object for dataset
        properties_content=$(jq -c '.properties' infra/pipelines/dataset_fontedados.json)
        az datafactory dataset create \
          --factory-name DataValidationFactoryUnique \
          --resource-group my-resource-group \
          --dataset-name FonteDados \
          --properties "$properties_content" # Pass only the properties object

    - name: Deploy DestinoDados Dataset
      run: |
        echo "Deploying DestinoDados Dataset..."
        # Extract properties object for dataset
        properties_content=$(jq -c '.properties' infra/pipelines/dataset_destinodados.json)
        az datafactory dataset create \\
          --factory-name DataValidationFactoryUnique \\
          --resource-group my-resource-group \\
          --dataset-name DestinoDados \\
          --properties "$properties_content" # Pass only the properties object

    # --- Adicionar novos passos aqui ---
    - name: Deploy NOAA ISD Linked Service
      run: |
        echo "Deploying NOAA ISD Linked Service..."
        properties_content=$(jq -c '.properties' infra/pipelines/linkedservice_noaa_isd.json)
        az datafactory linked-service create \\
          --factory-name DataValidationFactoryUnique \\
          --resource-group my-resource-group \\
          --linked-service-name AzureBlobStorageNOAAISD \\
          --properties "$properties_content"

    - name: Deploy NOAA ISD Source Dataset
      run: |
        echo "Deploying NOAA ISD Source Dataset..."
        properties_content=$(jq -c '.properties' infra/pipelines/dataset_noaa_isd.json)
        az datafactory dataset create \\
          --factory-name DataValidationFactoryUnique \\
          --resource-group my-resource-group \\
          --dataset-name NOAAISDSource \\
          --properties "$properties_content"
    # --- Fim dos novos passos ---

    # End of new steps

    - name: Validate Data Factory Creation
      run: |
        echo "Validating Azure Data Factory creation..."
        # Use single backslash for line continuation
        az datafactory show \
          --name DataValidationFactoryUnique \
          --resource-group my-resource-group

    - name: Deploy Data Factory pipelines
      run: |
        echo "Deploying Data Factory pipelines..."
        # Read the full pipeline content
        pipeline_content=$(cat infra/pipelines/ingestao.adf.json)
        # Use single backslash for line continuation
        az datafactory pipeline create \
          --factory-name DataValidationFactoryUnique \
          --resource-group my-resource-group \
          --name PipelineIngestao \
          --pipeline "$pipeline_content" # Pass the full pipeline definition

    - name: Register Resource Provider
      run: |
        echo "Registering microsoft.operationalinsights..."
        az provider register --namespace microsoft.operationalinsights

    - name: Validate Resource Provider Registration
      run: |
        echo "Validating registration of microsoft.operationalinsights..."
        az provider show --namespace microsoft.operationalinsights --query "registrationState"

    - name: Diagnose Bicep Deployment
      run: |
        echo "Diagnosing Bicep deployment..."
        az deployment group show \
          --resource-group my-resource-group \
          --name main

    - name: Validate Resource Group
      run: |
        echo "Validating resource group existence..."
        az group show --name my-resource-group

    - name: Validate Storage Account
      run: |
        echo "Validating Storage Account creation..."
        az storage account show --name datavalidation456 --resource-group my-resource-group # Name matches parameters.json

    - name: Validate SQL Server
      run: |
        echo "Validating SQL Server creation..."
        az sql server show --name datavalidation-sqlserver12345 --resource-group my-resource-group # Corrected name

