name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        echo "Creating resource group..."
        az group create \
          --name my-resource-group \
          --location eastus

    - name: Deploy Bicep template
      run: |
        echo "Deploying Bicep template..."
        az deployment group create \
          --resource-group my-resource-group \
          --template-file infra/main.bicep \
          --parameters @infra/parameters.json

    - name: Install Azure CLI Data Factory Extension
      run: |
        echo "Installing Azure CLI Data Factory extension..."
        az extension add --name datafactory --yes

    - name: Deploy Data Factory pipelines
      run: |
        echo "Deploying Data Factory pipelines..."
        az datafactory pipeline create \
          --factory-name DataValidationFactory \
          --resource-group my-resource-group \
          --name PipelineIngestao \
          --pipeline-file infra/pipelines/ingestao.adf.json

    - name: Deploy SQL Database
      run: |
        echo "Deploying SQL Server and Database..."
        az sql server create \
          --name datavalidation-sqlserver \
          --resource-group my-resource-group \
          --location eastus \
          --admin-user adminUser \
          --admin-password P@ssw0rd1234

        az sql db create \
          --resource-group my-resource-group \
          --server datavalidation-sqlserver \
          --name fictitiousdb \
          --service-objective Basic

    - name: Register Resource Provider
      run: |
        echo "Registering microsoft.operationalinsights..."
        az provider register --namespace microsoft.operationalinsights

    - name: Validate Resource Provider Registration
      run: |
        echo "Validating registration of microsoft.operationalinsights..."
        az provider show --namespace microsoft.operationalinsights --query "registrationState"

