name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        echo "Creating resource group..."
        az group create \
          --name my-resource-group \
          --location eastus

    - name: Deploy Bicep template
      run: |
        echo "Deploying Bicep template..."
        az deployment group create \
          --resource-group my-resource-group \
          --template-file infra/main.bicep \
          --parameters @infra/parameters.json

    - name: List Resources in Resource Group
      run: |
        echo "Listing resources in the group..."
        az resource list --resource-group my-resource-group

    - name: Install Azure CLI Data Factory Extension
      run: |
        echo "Installing Azure CLI Data Factory extension..."
        az extension add --name datafactory --yes

    # Steps to deploy Linked Service and Datasets
    - name: Get Storage Account Key
      id: storage_key
      run: |
        echo "Getting storage account key..."
        STORAGE_KEY=$(az storage account keys list --resource-group my-resource-group --account-name datavalidation456 --query "[0].value" -o tsv)
        # Use environment file for output
        echo "key=$STORAGE_KEY" >> $GITHUB_OUTPUT

    - name: Deploy Azure Blob Storage Linked Service
      run: |
        echo "Deploying Azure Blob Storage Linked Service..."
        properties_content=$(jq -c '.properties' infra/pipelines/linkedservice_blobstorage.json)
        properties_content=${properties_content/<STORAGE_ACCOUNT_NAME>/datavalidation456}
        properties_content=${properties_content/<STORAGE_ACCOUNT_KEY>/${{ steps.storage_key.outputs.key }}}
        # Use --name instead of --linked-service-name and remove line continuations
        az datafactory linked-service create --factory-name DataValidationFactoryUnique --resource-group my-resource-group --name AzureBlobStorageLinkedService --properties "$properties_content"

    - name: Deploy FonteDados Dataset
      run: |
        echo "Deploying FonteDados Dataset..."
        properties_content=$(jq -c '.properties' infra/pipelines/dataset_fontedados.json)
        # Use --name instead of --dataset-name and remove line continuations
        az datafactory dataset create --factory-name DataValidationFactoryUnique --resource-group my-resource-group --name FonteDados --properties "$properties_content"

    - name: Deploy DestinoDados Dataset
      run: |
        echo "Deploying DestinoDados Dataset..."
        properties_content=$(jq -c '.properties' infra/pipelines/dataset_destinodados.json)
        # Use --name instead of --dataset-name and remove line continuations
        az datafactory dataset create --factory-name DataValidationFactoryUnique --resource-group my-resource-group --name DestinoDados --properties "$properties_content"

    # --- Adicionar novos passos aqui ---
    - name: Deploy NOAA ISD Linked Service
      run: |
        echo "Deploying NOAA ISD Linked Service..."
        properties_content=$(jq -c '.properties' infra/pipelines/linkedservice_noaa_isd.json)
        # Use --name instead of --linked-service-name and remove line continuations
        az datafactory linked-service create --factory-name DataValidationFactoryUnique --resource-group my-resource-group --name AzureBlobStorageNOAAISD --properties "$properties_content"

    - name: Deploy NOAA ISD Source Dataset
      run: |
        echo "Deploying NOAA ISD Source Dataset..."
        properties_content=$(jq -c '.properties' infra/pipelines/dataset_noaa_isd.json)
        # Use --name instead of --dataset-name and remove line continuations
        az datafactory dataset create --factory-name DataValidationFactoryUnique --resource-group my-resource-group --name NOAAISDSource --properties "$properties_content"
    
    # Adicionar linked service do Databricks
    - name: Deploy Databricks Linked Service
      run: |
        echo "Deploying Databricks Linked Service..."
        properties_content=$(jq -c '.properties' infra/pipelines/linkedservice_databricks.json)
        # Use --name instead of --linked-service-name
        az datafactory linked-service create --factory-name DataValidationFactoryUnique --resource-group my-resource-group --name AzureDatabricks_LinkedService --properties "$properties_content"
    # --- Fim dos novos passos ---

    # End of new steps

    - name: Validate Data Factory Creation
      run: |
        echo "Validating Azure Data Factory creation..."
        az datafactory show \
          --name DataValidationFactoryUnique \
          --resource-group my-resource-group

    - name: Deploy Data Factory pipelines
      run: |
        echo "Deploying Data Factory pipelines..."
        # Pipeline de ingestão
        echo "Deploying ingestion pipeline..."
        pipeline_content=$(cat infra/pipelines/ingestao.adf.json)
        az datafactory pipeline create --factory-name DataValidationFactoryUnique --resource-group my-resource-group --name PipelineIngestao --pipeline "$pipeline_content"
        
        # Pipeline de transformação
        echo "Deploying transformation pipeline..."
        pipeline_content=$(cat infra/pipelines/transformacao.json)
        az datafactory pipeline create --factory-name DataValidationFactoryUnique --resource-group my-resource-group --name Pipeline_Transformacao_Databricks --pipeline "$pipeline_content"
        
        # Pipeline de monitoramento
        echo "Deploying monitoring pipeline..."
        pipeline_content=$(cat infra/pipelines/monitoramento.json)
        az datafactory pipeline create --factory-name DataValidationFactoryUnique --resource-group my-resource-group --name MonitorarPipelines --pipeline "$pipeline_content"

    - name: Register Resource Provider
      run: |
        echo "Registering microsoft.operationalinsights..."
        az provider register --namespace microsoft.operationalinsights

    - name: Validate Resource Provider Registration
      run: |
        echo "Validating registration of microsoft.operationalinsights..."
        az provider show --namespace microsoft.operationalinsights --query "registrationState"

    - name: Diagnose Bicep Deployment
      run: |
        echo "Diagnosing Bicep deployment..."
        az deployment group show \
          --resource-group my-resource-group \
          --name main

    - name: Validate Resource Group
      run: |
        echo "Validating resource group existence..."
        az group show --name my-resource-group

    - name: Validate Storage Account
      run: |
        echo "Validating Storage Account creation..."
        az storage account show --name datavalidation456 --resource-group my-resource-group # Name matches parameters.json

    - name: Validate SQL Server
      run: |
        echo "Validating SQL Server creation..."
        az sql server show --name datavalidation-sqlserver12345 --resource-group my-resource-group # Corrected name

